代码4-1 基于K-Means算法的航空公司客户价值细分的实现

In [7]:
import pandas as pd
from sklearn.cluster import KMeans#导入K均值聚类算法
import os

In [8]:
filepath=os.getcwd()#获取当前路径
inputfile=filepath+'/customerdata.xlsx'#当前路径下的客户数据
datanew=pd.read_excel(inputfile)
datanew=(datanew-datanew.mean(axis=0))/(datanew.std(axis=0))#对数据进行标准化操作
k=5#需要进行的聚类类别数
#调用K均值聚类算法，进行聚类分析
kmodel=KMeans(n_clusters=k)
kmodel.fit(datanew)

KMeans(copy_x=True, init='k-means++', max_iter=300, n_clusters=5, n_init=10,
    n_jobs=1, precompute_distances='auto', random_state=None, tol=0.0001,
    verbose=0)

In [9]:
datanew['type']=kmodel.labels_#将聚类结果合并入原始数据中，以便查看用户类型
print(datanew )#查看用户聚类结果

            C         F         L         M         R  type
0    0.389623 -0.761854 -0.943779 -0.622303  0.345849     1
1   -0.455902 -1.218966 -0.778595 -0.966680 -0.647152     1
2    0.462648 -1.218966  0.003956 -0.830110  1.960637     0
3   -0.140775  0.723761  1.546909 -0.189569 -0.350180     3
4    0.702319  0.495205  0.041791 -0.457396 -0.999807     2
5    0.160175  0.723761  1.188855  2.155541  1.552300     4
6    0.199846 -0.761854 -1.348897 -0.873797 -0.684274     1
7    0.341121 -0.876132  0.071322 -0.592588 -0.480105     2
8    0.347145 -1.333244  0.468134 -1.066254  2.897956     0
9    0.347409  1.980820  1.161171  4.127149 -0.554349     4
10   0.465001  0.609483  1.433402 -0.878520  1.208925     0
11   0.590153  1.637986  1.023671  0.940578 -0.146011     4
12   1.233496  0.152371  1.012597  0.181768  0.308728     2
13   1.310925 -0.304742  0.435835 -0.701412 -0.721396     2
14  -1.817265 -1.218966  0.118385 -0.849198 -0.925564     1
15  -1.782413  0.495205 -0.464836  1.881

In [10]:
print(kmodel.cluster_centers_ )#查看各聚类中心

[[ 0.18436904 -0.73588169  0.63017241 -0.61875208  1.81552518]
 [-0.20377188 -0.81598571 -1.10626831 -0.7752584  -0.45031049]
 [ 1.01832572 -0.01731486  0.07174107 -0.13506476 -0.11507682]
 [-1.05891722  0.55570526  0.45285298  0.26231765 -0.34581275]
 [ 0.26459346  1.25540286  0.45260635  1.67872617 -0.31628639]]


对聚类分析的结果进行可视化处理

In [11]:
#导入可视化需要的库
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import numpy as np

In [12]:
labels = np.array(['C','F','L','M','R'])#设置标签
dataLength = 5#设置数据长度
angles = np.linspace(0, 2*np.pi, dataLength, endpoint=False)#分割圆周长
angles = np.concatenate((angles, [angles[0]]))  # 闭合
fig = plt.figure(figsize=(5,5))#设置画布大小
ax = fig.add_subplot(111, polar=True)
ax.set_thetagrids(angles * 180/np.pi, labels, fontproperties="SimHei")#添加标签
ax.set_rlim(-2,2)
color=['ro-','bs--','gp:','y>-.','k*-']
for k in range(5):
    data=kmodel.cluster_centers_[k]
    data=np.concatenate((data, [data[0]]))#闭合
    ax.plot(angles,data,color[k],linewidth=1)
plt.title(u"五类用户特征雷达图",fontproperties="SimHei",fontsize=30)
plt.show()